# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: playLAN.playLAN
PackageVersion: 0.7.3
InstallerLocale: ru-RU
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ProductCode: '{8F3A1C2E-5D4B-4A6F-9E1B-2C7D9A0F4E15}_is1'
AppsAndFeaturesEntries:
- DisplayName: playLAN, версия 0.7.3
  Publisher: playLAN
  ProductCode: '{8F3A1C2E-5D4B-4A6F-9E1B-2C7D9A0F4E15}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://api.playlanapp.ru/dl/playLAN-setup-0.7.3.exe
  InstallerSha256: 9B7D842F127CD02F1A9F1B09B582B6782CD6CA74A27D29B3E31AD363FAA9C226
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-09-03
